export const AppConstAuthStrategy = {
  JWT_LOCAL_PASSWORD: 'WALNUT-JWT-LOCAL-PASSWORD',
  JWT_LOCAL_EMAIL: 'WALNUT-JWT-LOCAL-EMAIL',
  JWT_LOCAL_PHONE: 'WALNUT-JWT-LOCAL-PHONE',
  JWT_ACCESS_TOKEN: 'WALNUT-JWT-ACCESS-TOKEN',
  JWT_REFRESH_TOKEN: 'WALNUT-JWT-REFRESH-TOKEN',

  THIRD_PARTY_GITHUB: 'WALNUT-THIRD-PARTY-GITHUB',
  THIRD_PARTY_GITEE: 'WALNUT-THIRD-PARTY-GITEE',
  THIRD_PARTY_WEIBO: 'WALNUT-THIRD-PARTY-WEIBO',
} as const;
